name: OITQ
main: OITQ\Main
version: 1.0.3
api: [1.0.0]
load: POSTWORLD
author: EmreTr1
commands:
 oitq:
  permission: oitq.command.fsg
  description: TheQuiver
  usage: /tq <set|remove>
 lobby:
  permission: oitq.command.lobby
  description: lobiye doner
  usage: /lobby
permissions:
 oitq:
  description: hepsi
  default: op
  children:
   oitq.command:
    description: cocuk
    default: op
    children:
     oitq.command.lobby:
      description: lobi ye doner
      default: true
     oitq.command.oitq:
      description: TheQuiver
      default: op
   oitq.touch.startgame:
    description: TheQuiver
    default: true
